/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;import java.awt.Toolkit;
import java.awt.event.WindowEvent;

import com.itextpdf.text.pdf.BarcodePDF417;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

import org.iban4j.IbanFormatException;
import org.iban4j.IbanUtil ;
/**
 *
 * @author Bretan
 */
public class Principal extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String vnrdoc, vsuma,vnume_pl, vcif_pl, vadr_pl, viban_pl, vbic_pl, vnume_ben, vcif_ben, viban_ben, vbic_ben, vnrevid, voblig, vdata_pl, vcod_ct, vrd_ct, vcod_prog, bicpl;
    String vswift;
    private String JTextField;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conn = javaconnect.ConnecrDb();
        Incarca();
        this.txt_adica.setText(Main.sumacaract(this.txt_suma.getText()));
    }
    public void close(){
         WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING); 
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
         }
    public void Incarca(){
    try{
        String sqlincarca = "Select * from ordine";
        pst = conn.prepareStatement(sqlincarca);
        rs = pst.executeQuery();
        while(rs.next()){
        vnrdoc = rs.getString("nrdoc");
        vsuma = rs.getString("suma");
        vnume_pl = rs.getString("nume_pl");
        vcif_pl = rs.getString("cif_pl");
        vadr_pl = rs.getString("adr_pl");
        viban_pl = rs.getString("iban_pl");
        vbic_pl = rs.getString("bic_pl");
        vnume_ben = rs.getString("nume_ben");
        vcif_ben = rs.getString("cif_ben");
        viban_ben = rs.getString("iban_ben");
        vbic_ben = rs.getString("bic_ben");
        vnrevid = rs.getString("nrevid");
        voblig = rs.getString("oblig");
        vdata_pl = rs.getString("data_pl");
        vcod_ct = rs.getString("cod_ct");
        vrd_ct = rs.getString("rd_ct");
        vcod_prog = rs.getString("cod_prog");
        
        txt_nrdoc.setText(vnrdoc);
        txt_suma.setText(vsuma);
        txt_nume_pl.setText(vnume_pl);
        txt_cif_pl.setText(vcif_pl);
        txt_adr_pl.setText(vadr_pl);
        txt_iban_pl.setText(viban_pl);
        txt_bic_pl.setText(vbic_pl);
        txt_nume_ben.setText(vnume_ben);
        txt_cif_ben.setText(vcif_ben);
        txt_iban_ben.setText(viban_ben);
        txt_bic_ben.setText(vbic_ben);
        txt_nrevid.setText(vnrevid);
        txt_oblig.setText(voblig);
        txt_data_pl.setDate(null);
        //   idcurent = Integer.parseInt(curent);
    }
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    }
    public void getSwift(String biciban){
    try{
    //    String biciban = txt_iban_pl.getText().substring(4, 8);
    //   JOptionPane.showMessageDialog(null, "Cicul este: " + biciban, "Informare", 1);
        String sqlswift = "Select * from swift where bic = '"+biciban+"' ";
        
        pst = conn.prepareStatement(sqlswift);
        rs = pst.executeQuery();
        while(rs.next()){
        vswift = rs.getString("swift");
        txt_bic_pl.setText(vswift);
    }
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_adica = new javax.swing.JTextField();
        txt_nrdoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_suma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nume_pl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cif_pl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_adr_pl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_iban_pl = new javax.swing.JTextField();
        txt_bic_ben = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_cod_ct = new javax.swing.JTextField();
        txt_rd_ct = new javax.swing.JTextField();
        txt_cod_prog = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_nume_ben = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_cif_ben = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_iban_ben = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_banca_ben = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_nrevid = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        blistez = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txt_data_pl = new com.toedter.calendar.JDateChooser();
        txt_bic_pl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_oblig = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ORDIN DE PLATA");

        jLabel2.setText("Nr.");

        txt_adica.setEditable(false);
        txt_adica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_adica.setMargin(new java.awt.Insets(1, 2, 2, 2));

        txt_nrdoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("PLATITI");

        txt_suma.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel4.setText("LEI, adica:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("PLATITOR");

        txt_nume_pl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nume_pl.setMargin(new java.awt.Insets(1, 2, 2, 2));

        jLabel6.setText("Cod de identificare fiscala");

        txt_cif_pl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cif_pl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cif_plFocusLost(evt);
            }
        });

        jLabel7.setText("Adresa");

        txt_adr_pl.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Codul BIC");

        jLabel9.setText("Cod IBAN platitor");

        txt_iban_pl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_iban_pl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_iban_plFocusLost(evt);
            }
        });
        txt_iban_pl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_iban_plKeyReleased(evt);
            }
        });

        txt_bic_ben.setEditable(false);
        txt_bic_ben.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setText("De la");

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setText("Angajament:   Cod");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Indicator");

        jLabel14.setText("Cod program");

        jLabel15.setText("BENEFICIAR");

        txt_nume_ben.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel16.setText("Cod de identificare fiscala");

        txt_cif_ben.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cif_ben.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cif_benFocusLost(evt);
            }
        });

        jLabel17.setText("Codul BIC");

        jLabel18.setText("Cod IBAN beneficiar");

        txt_iban_ben.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_iban_ben.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_iban_benFocusLost(evt);
            }
        });
        txt_iban_ben.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_iban_benKeyReleased(evt);
            }
        });

        jLabel20.setText("La");

        txt_banca_ben.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel21.setText("Nr. de evidenta a platii");

        jLabel22.setText("Reprezentand");

        jLabel23.setText("(Sucursala)");

        jLabel24.setText("(Sucursala)");

        jLabel25.setText("Data emiterii");

        jButton2.setText("Iesire");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        blistez.setText("Listare");
        blistez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blistezActionPerformed(evt);
            }
        });

        jLabel26.setText("Localitate...");

        txt_data_pl.setDateFormatString(" dd/MM/yyyy");

        txt_bic_pl.setEditable(false);
        txt_bic_pl.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_oblig.setColumns(20);
        txt_oblig.setRows(5);
        jScrollPane1.setViewportView(txt_oblig);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nume_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(383, 383, 383))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_nrdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(txt_adica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_iban_ben, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_cif_ben, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel17))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(txt_bic_ben, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cod_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_rd_ct, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addGap(397, 397, 397))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21))
                                        .addGap(37, 37, 37)
                                        .addComponent(txt_nrevid))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel15))
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel23)))
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_data_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField21)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_banca_ben, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_iban_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_bic_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_cod_prog, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_nume_ben, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField20)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(txt_cif_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)
                                .addGap(75, 75, 75))
                            .addComponent(txt_adr_pl, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blistez, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(212, 212, 212))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nrdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txt_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_adica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nume_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blistez))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cif_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_adr_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_iban_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bic_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cod_prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rd_ct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cod_ct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nume_ben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_cif_ben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_iban_ben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(txt_bic_ben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_banca_ben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nrevid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txt_data_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("OP", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blistezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blistezActionPerformed
      String datosv = this.creaza_dtos_pdfv();
        if (datosv.indexOf("#") >= 0) {
            JOptionPane.showMessageDialog(null, "Cimpurile contin caracterul # care este interzis ", "Eroare", 0);
            this.blistez.requestFocus();
            return;
        }
        if (this.txt_nrdoc.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "Lungimea cimpului nrdoc e de maxim 10 caractere", "Eroare", 0);
            this.txt_nrdoc.requestFocus();
            return;
        }
        if (this.txt_suma.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "Lungimea cimpului Suma e de maxim 15 caractere", "Eroare", 0);
            this.blistez.requestFocus();
            return;
        }
        String datos = this.creaza_dtos_pdf();
//         JOptionPane.showMessageDialog(null, "Datos este: " + datos, "Informare", 1);
        try {
            File f = new File("coduri_bara.txt");
            if (f.exists()) {
                f.delete();
            }
            FileWriter out = new FileWriter("coduri_bara.txt");
            out.write(datos);
            out.close();
            File ftxt = new File("coduri_bara.txt");
            if (!ftxt.exists()) {
                JOptionPane.showMessageDialog(null, "Eroare", "Fisierul coduri_bara.txt nu s-a generat reia listarea", 0);
                return;
            }
        }
        catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
   //     JOptionPane.showMessageDialog(null, "Informare", "fisier txt generat", 1);
//       JOptionPane.showMessageDialog(null, "Informare", "Sumtem inainte de bmp(datos)", 1);
        this.creaza_BMP(datos);
//        JOptionPane.showMessageDialog(null, "Informare", "fisier bmp generat2(datos)", 1);
//        this.afisareBmp();
//        try {
//       this.creaza_lista_PDF();
//        }
//        catch (DocumentException ex) {
//            JOptionPane.showMessageDialog(null, "Eroare creare document PDF", "Eroare creare document PDF", 0);
//        }
//        catch (FileNotFoundException ex) {
//            JOptionPane.showMessageDialog(null, "Eroare creare fisier PDF", "Eroare creare fisier PDF", 0);
//        }
//        catch (IOException ex) {
//            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
 //       } 
    }//GEN-LAST:event_blistezActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_iban_plKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_iban_plKeyReleased
   
    }//GEN-LAST:event_txt_iban_plKeyReleased

    private void txt_iban_plFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_iban_plFocusLost
       String bicibanp = txt_iban_pl.getText().substring(4, 8);
        getSwift(bicibanp);
        String vibanp = txt_iban_pl.getText();
        try {
         IbanUtil.validate(vibanp);
    // valid
//          JOptionPane.showMessageDialog(null, "Informare", "Iban valid", 1);
        } catch (IbanFormatException e) {
            JOptionPane.showMessageDialog(null, "Eroare", "Iban invalid", 0);
    // invalid
            }
    }//GEN-LAST:event_txt_iban_plFocusLost

    private void txt_iban_benKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_iban_benKeyReleased
       
    }//GEN-LAST:event_txt_iban_benKeyReleased

    private void txt_iban_benFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_iban_benFocusLost
       String bicibanb = txt_iban_ben.getText().substring(4, 8);
        getSwift(bicibanb);
        String vibanben = txt_iban_ben.getText();
           try {
         IbanUtil.validate(vibanben);
        } catch (IbanFormatException e) {
            JOptionPane.showMessageDialog(null, "Eroare", "Iban invalid", 0);
        }
    }//GEN-LAST:event_txt_iban_benFocusLost

    private void txt_cif_plFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cif_plFocusLost
       if (this.txt_cif_pl.isEnabled() && this.txt_cif_pl.isEditable()) {
            try {
                double cpl = Double.parseDouble(this.txt_cif_pl.getText());
                if (cpl <= 0.0) {
                    JOptionPane.showMessageDialog(null, "cod fiscal platitor incorect, trebuie sa fie numeric", "Eroare", 0);
                    this.txt_cif_pl.requestFocus();
                }
            }
            catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "cod fiscal platitor incorect, trebuie sa fie numeric", "Eroare", 0);
                this.txt_cif_pl.requestFocus();
                return;
            }
            int vcui = Main.verif_cui(this.txt_cif_pl.getText());
            if (vcui != 0) {
                JOptionPane.showMessageDialog(null, "Eroare", "cod fiscal platitor incorect", 0);
                this.txt_cif_pl.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_cif_plFocusLost

    private void txt_cif_benFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cif_benFocusLost
       if (this.txt_cif_ben.isEnabled() && this.txt_cif_ben.isEditable()) {
            try {
                double cpl = Double.parseDouble(this.txt_cif_ben.getText());
                if (cpl <= 0.0) {
                    JOptionPane.showMessageDialog(null, "cod fiscal platitor incorect, trebuie sa fie numeric", "Eroare", 0);
                    this.txt_cif_ben.requestFocus();
                }
            }
            catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "cod fiscal platitor incorect, trebuie sa fie numeric", "Eroare", 0);
                this.txt_cif_ben.requestFocus();
                return;
            }
            int vcui = Main.verif_cui(this.txt_cif_ben.getText());
            if (vcui != 0) {
                JOptionPane.showMessageDialog(null, "Eroare", "cod fiscal platitor incorect", 0);
                this.txt_cif_pl.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_cif_benFocusLost

    private void creaza_BMP(String pdatos) {
        try {
            BarcodePDF417 pdf417 = new BarcodePDF417();
            pdf417.setText(pdatos);
            Image rawImage = pdf417.createAwtImage(Color.BLACK, Color.WHITE);
            BufferedImage outImage = new BufferedImage(rawImage.getWidth(null), rawImage.getHeight(null), 1);
            outImage.getGraphics().drawImage(rawImage, 0, 0, null);
             JOptionPane.showMessageDialog(null, "Pdatos este: " + pdatos, "Informare", 1);
            File f = new File("coduri_bara.bmp");
            if (f.exists()) {
                f.delete();
            }
            ImageIO.write((RenderedImage)outImage, "bmp", f);
            JOptionPane.showMessageDialog(null, "Informare", "fisier bmp generat1(datos)", 1);
        }
        catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } 
        JOptionPane.showMessageDialog(null, "Informare", "Fisier bmp generat", 1);
      }
    
    private String creaza_dtos_pdf() {
        Locale locale = new Locale("en", "UK");
        String pattern = "###.##";
        DecimalFormat decimalFormat = (DecimalFormat)NumberFormat.getNumberInstance(locale);
        decimalFormat.applyPattern(pattern);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String data_pl = dateFormat.format(txt_data_pl.getDate());
        String datos = "";
        String datosv = "";
        datos = datos + "#" + this.txt_nrdoc.getText() + "#," + this.txt_suma.getText() + ",#" + this.txt_nume_pl.getText() + "#," + this.txt_cif_pl.getText() + ",#" + this.txt_adr_pl.getText() + "#,#";
        datosv = datosv + this.txt_nrdoc.getText() + this.txt_suma.getText() + this.txt_nume_pl.getText() + this.txt_cif_pl.getText() + this.txt_adr_pl.getText();
        datos = datos+ this.txt_iban_pl.getText() + "#,#" + this.txt_bic_pl.getText() + "#,#" + this.txt_nume_ben.getText() + "#," + this.txt_cif_ben.getText() + ",#" + this.txt_iban_ben.getText() + "#,#";
        datosv = datosv+ this.txt_iban_pl.getText() + this.txt_bic_pl.getText() + this.txt_nume_ben.getText() + this.txt_cif_ben.getText() + this.txt_iban_ben.getText();
        datos = datos + this.txt_bic_ben.getText() +"#," + this.txt_nrevid.getText() + ",#" + this.txt_oblig.getText() + "#," + data_pl + ",#" + this.txt_cod_ct.getText() + "#,#" + this.txt_rd_ct.getText() + "#," + this.txt_cod_prog.getText() + "#,";
        datosv = datosv + this.txt_bic_ben.getText() +this.txt_nrevid.getText() + this.txt_oblig.getText() + data_pl + this.txt_cod_ct.getText() + this.txt_rd_ct.getText()+ this.txt_cod_prog.getText();
        JOptionPane.showMessageDialog(null, "Datosv este: " + datosv, "Informare", 1);
        try {
       //    }
        }
        catch (NullPointerException ex) {
            System.out.println("txt_suma = 0");
        }
        return datos;
    }
    
        private String creaza_dtos_pdfv() {
        Locale locale = new Locale("en", "UK");
        String pattern = "###.##";
        DecimalFormat decimalFormat = (DecimalFormat)NumberFormat.getNumberInstance(locale);
        decimalFormat.applyPattern(pattern);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String data_pl = dateFormat.format(this.txt_data_pl.getDate());
        String datosv = "";
        datosv = datosv + this.txt_nrdoc.getText() + this.txt_suma.getText() + this.txt_nume_pl.getText() + this.txt_cif_pl.getText() + this.txt_adr_pl.getText();
        datosv = datosv+ this.txt_iban_pl.getText() + this.txt_bic_pl.getText() + this.txt_nume_ben.getText() + this.txt_cif_ben.getText() + this.txt_iban_ben;
        datosv = datosv + this.txt_bic_ben.getText() +this.txt_nrevid.getText() + this.txt_oblig.getText() + data_pl + this.txt_cod_ct.getText() + this.txt_rd_ct.getText()+ this.txt_cod_prog.getText();
        try {
         //    }
        }
        catch (NullPointerException ex) {
            System.out.println("Suma = 0");
        }
        return datosv;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blistez;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txt_adica;
    private javax.swing.JTextField txt_adr_pl;
    private javax.swing.JTextField txt_banca_ben;
    private javax.swing.JTextField txt_bic_ben;
    private javax.swing.JTextField txt_bic_pl;
    private javax.swing.JTextField txt_cif_ben;
    private javax.swing.JTextField txt_cif_pl;
    private javax.swing.JTextField txt_cod_ct;
    private javax.swing.JTextField txt_cod_prog;
    private com.toedter.calendar.JDateChooser txt_data_pl;
    private javax.swing.JTextField txt_iban_ben;
    private javax.swing.JTextField txt_iban_pl;
    private javax.swing.JTextField txt_nrdoc;
    private javax.swing.JTextField txt_nrevid;
    private javax.swing.JTextField txt_nume_ben;
    private javax.swing.JTextField txt_nume_pl;
    private javax.swing.JTextArea txt_oblig;
    private javax.swing.JTextField txt_rd_ct;
    private javax.swing.JTextField txt_suma;
    // End of variables declaration//GEN-END:variables
}
